// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ5iGdlvZmBvVOpRUDh7_6LfpLHFx6CoA',
    appId: '1:147111301200:web:f7f83a90c0aad41b3c0155',
    messagingSenderId: '147111301200',
    projectId: 'nutri-a6e15',
    authDomain: 'nutri-a6e15.firebaseapp.com',
    storageBucket: 'nutri-a6e15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76ImnrKjotd16BSspwPTkWp4Wtbnb2ko',
    appId: '1:147111301200:android:7858f337e3edc3dd3c0155',
    messagingSenderId: '147111301200',
    projectId: 'nutri-a6e15',
    storageBucket: 'nutri-a6e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucfnOlcrr9lM9oHewuoaD5j1IMuOAmPc',
    appId: '1:147111301200:ios:f0a5285d338417273c0155',
    messagingSenderId: '147111301200',
    projectId: 'nutri-a6e15',
    storageBucket: 'nutri-a6e15.firebasestorage.app',
    iosBundleId: 'com.example.nutrikita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucfnOlcrr9lM9oHewuoaD5j1IMuOAmPc',
    appId: '1:147111301200:ios:f0a5285d338417273c0155',
    messagingSenderId: '147111301200',
    projectId: 'nutri-a6e15',
    storageBucket: 'nutri-a6e15.firebasestorage.app',
    iosBundleId: 'com.example.nutrikita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ5iGdlvZmBvVOpRUDh7_6LfpLHFx6CoA',
    appId: '1:147111301200:web:feb16dc6b7f573c83c0155',
    messagingSenderId: '147111301200',
    projectId: 'nutri-a6e15',
    authDomain: 'nutri-a6e15.firebaseapp.com',
    storageBucket: 'nutri-a6e15.firebasestorage.app',
  );
}
