name: nutrikita
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  fl_chart: ^1.0.0
  intl: ^0.19.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  image_picker: ^1.0.4
  firebase_storage: ^12.4.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.0.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logos/nutrikita.png
    - assets/logos/google.png
    - assets/icons/indikator.png
    - assets/icons/laporan.png
    - assets/icons/peringatan.png
    - assets/icons/sekolah.png
    - assets/icons/siswa.png
    - assets/icons/status.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
